### PR TITLE
Release-v1.21.3-patchX: Backport Base64 and Substring Transformation Functions (#184)

### PR DESCRIPTION
**Pull request by ben-taussig-solo**
Backport #184 to release-v1.21.3-patchX, for use in Gloo Edge OSS v1.11.x

### CODE REVIEW

**Comment by ben-taussig-solo** [comment]
changelog-bot is failing because this is marked as a `NEW_FEATURE`. We will need to `skip-changelog` before merging this.

**Review by nfuden — APPROVED** [review]
Nice backport

**Pull request merged**
