### PR TITLE
Remote cache

### PR DESCRIPTION
**Pull request by kdorosh**

### CODE REVIEW

**Comment by kdorosh** [comment]
resolves https://github.com/solo-io/envoy-gloo-ee/issues/209

**Comment by kdorosh** [comment]
/kick new build-bot supports `availableSecrets` api now

**Comment by kdorosh** [comment]
/kick original build passed in 1:09, now that cache is populated this should be much quicker. original logs: https://console.cloud.google.com/cloud-build/builds;region=global/7260f819-7996-4d66-b3c7-def473c66d6f?project=solo-public

**Comment by yuval-k** [comment]
/kick original build passed in 1:07, now that cache is populated this should be much quicker. original logs:
https://console.cloud.google.com/cloud-build/builds;region=global/f6a066bf-ef43-4fe2-bd6b-d8223db4ba91?project=solo-public

**Comment by kdorosh** [comment]
new build finished in about 10 minutes! https://console.cloud.google.com/cloud-build/builds;region=global/ce30fcfa-8443-4eef-be21-d67a8767688b?project=solo-public

**Review by yuval-k — APPROVED** [review]

**Pull request merged**
